openapi: 3.0.0

paths:
  /customer/{customer_id}:
    get:
      summary: Returns the main information about a customer
      parameters:
        - name: cutomer_id
          in: path
          required: true
          description: customer ID
        - in: query
          name: date
          required: false
          description: date
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getCustomer/invocations"
        httpMethod: "POST"
    put:
      summary: Create or update information for the customer
      parameters:
        - name: customer_id
          in: path
          required: true
          description: customer ID
      requestBody:
        required: true
        description: customer ID
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_name:
                  type: string
                residence:
                  type: string
                times_used_service:
                  type: number
                email:
                  type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putCustomer/invocations"
        httpMethod: "POST"
  /package/{package_id}:
    get:
      summary: Returns the main information about a package
      parameters:
        - name: package_id
          in: path
          required: true
          description: package ID
        - in: query
          name: date
          required: false
          description: date
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getPackage/invocations"
        httpMethod: "POST"
    put:
      summary: Create or update information of the pack
      parameters:
        - name: package_id
          in: path
          required: true
          description: package ID
      requestBody:
        required: true
        description: package ID
        content:
          application/json:
            schema:
              type: object
              properties:
                dimentions:
                  type: number
                weigth:
                  type: number
                type_package:
                  type: string
                distance:
                  type: number
                origin:
                  type: string
                destination:
                  type: string
                estimated_price:
                  type: number
                discounts:
                  type: number
                total_price:
                  type: number
                date_registered:
                  type: string
                state:
                  type: string
                state_done:
                  type: boolean
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putPackage/invocations"
        httpMethod: "POST"
  /customer/{customer_id}/package/{package_id}:
    get:
      summary: Given a customer and a package displays the state of the package
      parameters:
        - name: customer_id
          in: path
          required: true
          description: customer ID
        - name: package_id
          in: path
          required: true
          description: package ID
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getCustomerPackageState/invocations"
        httpMethod: "POST" 